# Generated by Django 6.0.3 on 2026-03-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='name',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='num_seasons',
        ),
        migrations.AddField(
            model_name='anime',
            name='cast_star',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='gross_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='runtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='title',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='writer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='year_of_release',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='main_character',
            field=models.CharField(max_length=200),
        ),
    ]
