# Generated by Django 6.0.3 on 2026-03-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0002_remove_anime_name_remove_anime_num_seasons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='cast_star',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('sci_fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('animation', 'Animation'), ('documentary', 'Documentary')], max_length=30),
        ),
        migrations.AlterField(
            model_name='anime',
            name='gross_revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='main_character',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='writer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
