# Generated by Django 6.0.3 on 2026-03-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0003_alter_anime_cast_star_alter_anime_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'), ('NR', 'Not Rated')], max_length=10, null=True),
        ),
    ]
