# Generated by Django 6.0.3 on 2026-03-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0004_alter_anime_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('blaxploitation', 'Blaxploitation'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('sci_fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('animation', 'Animation'), ('documentary', 'Documentary')], max_length=30),
        ),
    ]
